name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions:
      contents: write
    uses: eclipse-docks/core/.github/workflows/app-release.yml@main
    with:
      base_path: /wattmonitormap/
      publish_dir: ./packages/app/dist
    secrets: inherit
