name: Auto Tag on Version Commit

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: eclipse-docks/core/.github/workflows/app-release.yml@main
    with:
      base_path: /wattmonitormap/
      publish_dir: ./packages/app/dist
    secrets: inherit
